[tool.poetry]
name = "pentest-py"
version = "0.1.0"
description = ""
authors = ["LianSheng197 <ci.i.cxcvii@gmail.com>"]
readme = "README.md"
# packages = [{include = "pentest"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
